### ISSUE TITLE
Fazit ergänzt, letzte Arbeiten

### ISSUE THREAD

**Issue by fabianlemmes** [fabianlemmes/T9.1_MALIS_20.3#6]
Liebe Chantal,

wie im anderen Issue erwähnt, habe ich in der Zwischenzeit das Fazit ergänzt. Du findest es nun im Dokument!

Deine Rückmeldung miteinbezogen bleiben für mich morgen noch folgende Arbeiten zu erledigen (die ich hier in einer kleinen Liste ablege, um sie für mich selbst morgen abhaken zu können ...):

- [x] Externe und interne Links im Dokument ergänzen.
- [x] Fußnoten erstellen, um den Textfluss im Haupttext zu verbessern.
- [x] Korrekturlesen und letzte Änderungen einarbeiten.

Und das sollte es dann gewesen sein ...!

Damit schon jetzt: vielen lieben Dank für Deine Mühe und die konstruktiven Rückmeldungen! Ich hoffe, ich konnte sie gut umsetzen ...

Beste Grüße, Fabian

**Comment by ckoeppl** [comment]
Lieber Fabian,

klasse, so passt doch alles doch noch!

Super finde ich deine wirklich sinnvollen und zahlreichen Navigationsmöglichkeiten und deren Umsetzung, inkls. Icons.

Zwei Dinge fielen mir jetzt beim allerletzten Drüberlesen

**Comment by ckoeppl** [comment]
Lieber Fabian,

klasse, so passt doch alles doch noch!

Super finde ich deine wirklich sinnvollen und zahlreichen Navigationsmöglichkeiten und deren Umsetzung, inkls. Icons.

Zwei Dinge fielen mir jetzt beim allerletzten Darüberlesen noch auf:

- [ ] einmal ist von "Schlagworten" die Rede, statt von "Schlagwörtern"
- [ ] einmal ist nur von "Ersteller" die Rede. Hier müsstest du politisch korrekt noch gendern 😅 

Und eine kurze Rückfrage: Die Verwendung des Begriffs "Data Literacy" kam für mich irgendwie überraschend, wenn es um die Automatisierung der beschriebenen Prozesse geht. Nur zum Verständnis: den hast du angeführt, weil die Promovenden in der Vergabe von Metadaten besser geschult werden müssten und du dir davon eine bessere Metadatenqualität erhoffst, bzw. eine Entlastung des bibliothekarischen Personals?

Viele Grüße
Chantal

**Comment by fabianlemmes** [comment]
Liebe Chantal,

auch vielen Dank für diese Rückmeldung! Im Einzelnen:

> - [ ] einmal ist von "Schlagworten" die Rede, statt von "Schlagwörtern"

Das ist ein "Zitat": steht so auf unserer OPUS-Seite.

> - [ ] einmal ist nur von "Ersteller" die Rede. Hier müsstest du politisch korrekt noch gendern 😅

Diese Stelle kann ich nicht finden ... Mag sein, dass ich es schon korrigiert hatte.

Beste Grüße, Fabian
